### ISSUE TITLE
Refresh Token Allows User to Specify Any Email Address

### ISSUE THREAD

**Issue by ardalis** [evgomes/jwt-api#14]
This code in AuthenticationService doesn't check that the email address in question is associated with the refresh token, so a common user could supply an admin user's email address when hitting /api/token/refresh and as long as the email exists, they will get an access token with that user's claims.

https://github.com/evgomes/jwt-api/blob/master/src/JWTAPI/JWTAPI/Services/AuthenticationService.cs#L49-L53

I have a version of this repo I'm using here which corrects the issue by associating refresh tokens with their user emailaddresses when they are created and when they are accessed:

https://github.com/ardalis/WebApiBestPractices/blob/main/securing_apis/jwtapi/Services/AuthenticationService.cs#L39-L40

HTH

**Comment by evgomes** [comment]
Hi @ardalis 

Thank you for reporting this problem, this is a huge security issue!

I fixed the validation to consider the email address based on the source code you provided. The routes to refresh tokens and to revoke refresh tokens should be safe now.

Please, let me know if you find any other issues. Thank you again for reporting the issue and for sending the link with your solution for it :)

**Comment by ardalis** [comment]
You bet! Thanks for accepting it and for creating this repo. I reference it in my latest Pluralsight course, ASP.NET Core 6 Web API Best Practices, which has a repo here: 
https://github.com/ardalis/WebApiBestPractices
