### ISSUE TITLE
User reference 

### ISSUE THREAD

**Issue by azufre** [evgomes/jwt-api#4]
It is not necessary to make reference to the user because there is no use of it

https://github.com/evgomes/jwt-api/blob/b011c29a11113db16a43d6c6b64f168e57d2e66b/src/JWTAPI/JWTAPI/Security/Tokens/TokenHandler.cs#L54

**Comment by evgomes** [comment]
Hi @azufre,

I'm closing this since I merged the code fix on #5.

Thank you!
