### ISSUE TITLE
Bug in TokenHandler.cs class

### ISSUE THREAD

**Issue by vurso** [evgomes/jwt-api#6]
Hi, cloned your repo and found the build failed due to this method in the TokenHandler.cs class:

        public AccessToken CreateAccessToken(User user)
        {
             ....
        }

The line:

var refreshToken = BuildRefreshToken(user);

Should be var refreshToken = BuildRefreshToken();

**Comment by evgomes** [comment]
Hi @vurso 

I'm sorry for replying so late, I have been really busy lately, so I could not check it before.

I fixed this issue, as well as I have updated the API to ASP.NET Core 3.1. Please, take a look at the updated code.

Thank you.
